title: My Blog
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beatriz-yun.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Sehui-Yoon
author-image:   sehui2.jpg
author-job:     Developer
author-email:    # Add your email for contant form.
author-twitter:  # Add your twitter account
about-author:   Always hungry to keep learning.

# Social settings
social-twitter:
social-facebook:
social-github:    Beatriz-Yun
social-pinterest:
social-instagram: the_huistle
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-192049021-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: beatriz-yun-github-io # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
